import { db } from "@/db";
import { legalGuides, scamRegistry, hustles } from "@/db/schema";

type SeedHustle = {
  slug: string;
  nameTl: string;
  nameEn: string;
  emoji?: string;
  category: string;
  descriptionTl: string;
  descriptionEn: string;
  incomeMinPhp: number;
  incomeMaxPhp: number;
  capitalMinPhp: number;
  capitalMaxPhp: number;
  hoursMinPerWeek: number;
  hoursMaxPerWeek?: number;
  timeToFirstPesoDays: number;
  breakevenMonths?: number;
  difficulty: "easy" | "medium" | "hard";
  regions: string[];
  requiresDevices: string[];
  requiresInternet: string;
  skillsRequired: string[];
  legalRequirements: string[];
  prosTl: string[];
  consTl: string[];
  commonMistakesTl: string[];
  steps: unknown[];
  suppliers: unknown[];
  legitimacyScore: number;
  isTrending?: boolean;
  unitLabel?: string;
  avgPhpPerUnit?: number;
  successStoryTl?: string;
};

const H = (h: SeedHustle) => h;

const sampleHustles: SeedHustle[] = [
  // ─────────────────────── ONLINE / REMOTE ───────────────────────
  H({
    slug: "virtual-assistant",
    nameTl: "Virtual Assistant (VA)",
    nameEn: "Virtual Assistant",
    category: "Online / Remote",
    descriptionTl:
      "Tumulong sa clients (PH o abroad) sa admin tasks: email, research, calendar, data entry, basic Canva. Stable at pwedeng maging full-time.",
    descriptionEn:
      "Help clients with admin tasks: email, research, calendar, data entry. Stable with full-time potential.",
    incomeMinPhp: 15000,
    incomeMaxPhp: 60000,
    capitalMinPhp: 0,
    capitalMaxPhp: 1000,
    hoursMinPerWeek: 10,
    hoursMaxPerWeek: 30,
    timeToFirstPesoDays: 14,
    breakevenMonths: 0,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["laptop"],
    requiresInternet: "prepaid_wifi",
    skillsRequired: ["communication", "english", "admin"],
    legalRequirements: ["BIR (kung consistent na ang income)"],
    prosTl: ["Mataas ang kita ceiling", "Remoto / work-from-home", "Walang puhunan"],
    consTl: ["Mataas ang competition", "Kailangan ng portfolio", "Graveyard shift sa US clients"],
    commonMistakesTl: [
      "Nag-aapply sa mga may 'training fee' o 'registration fee' — scam iyon",
      "Walang malinaw na niche o service package",
      "Underpricing habang tumatagal",
    ],
    steps: [
      {
        title: "Hakbang 1: Portfolio",
        items: [
          "Gumawa ng one-page profile (Google Docs/Notion) + 2–3 sample works",
          "Ilista ang services: inbox mgmt, research, calendar, data entry",
        ],
      },
      {
        title: "Hakbang 2: Mag-apply sa legit platforms",
        items: [
          "OnlineJobs.ph, Upwork, o direct sa FB groups ng business owners",
          "Iwasan ang kahit anong humihingi ng bayad bago ka mag-start",
        ],
      },
    ],
    suppliers: [
      {
        title: "Platforms",
        links: [
          { label: "OnlineJobs.ph", url: "https://www.onlinejobs.ph/" },
          { label: "Upwork", url: "https://www.upwork.com/" },
        ],
      },
    ],
    legitimacyScore: 5,
    isTrending: true,
    unitLabel: "kliyente/buwan",
    avgPhpPerUnit: 15000,
    successStoryTl:
      "Halimbawa (illustrative): Si Mara, 25, dating fast-food crew sa QC. Nag-self-study ng Google Workspace at Canva sa YT, nag-portfolio, at after 2 buwan ng pag-apply ay nakakuha ng part-time client sa $5/hr. Ngayon, kumikita siya ng ~₱35K/buwan habang nasa bahay.",
  }),
  H({
    slug: "online-esl",
    nameTl: "Online ESL Teaching",
    nameEn: "Online ESL Teaching",
    category: "Online / Remote",
    descriptionTl:
      "Magturo ng English online (51Talk, RareJob, Cambly). Entry-friendly, structured lessons, bayad per oras.",
    descriptionEn: "Teach English online (51Talk, RareJob, Cambly). Paid per hour.",
    incomeMinPhp: 12000,
    incomeMaxPhp: 35000,
    capitalMinPhp: 0,
    capitalMaxPhp: 1000,
    hoursMinPerWeek: 15,
    hoursMaxPerWeek: 30,
    timeToFirstPesoDays: 21,
    breakevenMonths: 0,
    difficulty: "easy",
    regions: ["Nationwide"],
    requiresDevices: ["laptop"],
    requiresInternet: "prepaid_wifi",
    skillsRequired: ["teaching", "english", "communication"],
    legalRequirements: ["BIR (self-employed)"],
    prosTl: ["Structured lessons", "May training", "Recurring students"],
    consTl: ["Peak hours ay gabi/umaga", "Kailangan tahimik na space"],
    commonMistakesTl: ["Walang backup internet", "Di nag-aabot ng minimum hours"],
    steps: [
      {
        title: "Simulan",
        items: [
          "Mag-apply sa 51Talk / RareJob / Cambly",
          "I-ready ang demo lesson at quiet room",
          "I-lock ang consistent na schedule para sa retention",
        ],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "oras",
    avgPhpPerUnit: 200,
  }),
  H({
    slug: "freelance-writing",
    nameTl: "Freelance Writing / Copywriting",
    nameEn: "Freelance Writing / Copywriting",
    category: "Online / Remote",
    descriptionTl:
      "Sumulat ng blog posts, product descriptions, emails, at ads para sa mga clients. Mababa ang puhunan, mataas ang ceiling.",
    descriptionEn: "Write blogs, product descriptions, emails, and ads for clients.",
    incomeMinPhp: 10000,
    incomeMaxPhp: 50000,
    capitalMinPhp: 0,
    capitalMaxPhp: 0,
    hoursMinPerWeek: 10,
    hoursMaxPerWeek: 25,
    timeToFirstPesoDays: 14,
    breakevenMonths: 0,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["laptop"],
    requiresInternet: "prepaid_wifi",
    skillsRequired: ["writing", "english"],
    legalRequirements: ["BIR (kung lumaki na)"],
    prosTl: ["₱0 puhunan", "Scalable per piece", "Pwede habang may trabaho"],
    consTl: ["Kailangan ng samples", "May revision cycles"],
    commonMistakesTl: ["Walang niche", "Di nag-i-edit bago isumite"],
    steps: [
      {
        title: "Simulan",
        items: [
          "Magsulat ng 3 sample articles (Medium/Notion)",
          "Mag-offer sa FB groups, OnlineJobs.ph, o local businesses",
          "Simula sa ₱500–₱1,000 per article, taasan habang may reviews",
        ],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "artikulo",
    avgPhpPerUnit: 1000,
  }),
  H({
    slug: "video-editing",
    nameTl: "Video Editing (CapCut/Premiere)",
    nameEn: "Video Editing",
    category: "Online / Remote",
    descriptionTl:
      "Mag-edit ng short-form content para sa creators at negosyo. Sobrang in-demand dahil sa TikTok/Reels.",
    descriptionEn: "Edit short-form content for creators and businesses.",
    incomeMinPhp: 12000,
    incomeMaxPhp: 60000,
    capitalMinPhp: 0,
    capitalMaxPhp: 0,
    hoursMinPerWeek: 10,
    hoursMaxPerWeek: 30,
    timeToFirstPesoDays: 10,
    breakevenMonths: 0,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["laptop"],
    requiresInternet: "prepaid_wifi",
    skillsRequired: ["video_editing", "content"],
    legalRequirements: ["BIR (kung lumaki na)"],
    prosTl: ["Mataas ang demand", "Pwede per video o retainer"],
    consTl: ["Rendering time", "Kailangan powerful-enough na laptop"],
    commonMistakesTl: ["Walang pricing tiers", "Di nag-ba-backup ng files"],
    steps: [
      {
        title: "Simulan",
        items: [
          "Gumawa ng 3 sample edits (30–60s) at i-post",
          "DM ang micro-creators at small businesses",
          "Package: per video o weekly retainer",
        ],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    isTrending: true,
    unitLabel: "video",
    avgPhpPerUnit: 2500,
  }),
  H({
    slug: "graphic-design",
    nameTl: "Graphic Design (Canva/Figma)",
    nameEn: "Graphic Design",
    category: "Online / Remote",
    descriptionTl:
      "Gumawa ng social media graphics, logos, posters para sa MSMEs at creators. Pwedeng magsimula sa Canva.",
    descriptionEn: "Create social media graphics, logos, and posters for MSMEs.",
    incomeMinPhp: 8000,
    incomeMaxPhp: 45000,
    capitalMinPhp: 0,
    capitalMaxPhp: 500,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 20,
    timeToFirstPesoDays: 14,
    breakevenMonths: 0,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["laptop"],
    requiresInternet: "prepaid_wifi",
    skillsRequired: ["graphic_design"],
    legalRequirements: ["BIR (kung lumaki na)"],
    prosTl: ["₱0 start sa Canva", "Maraming small businesses ang kliyente"],
    consTl: ["Price-sensitive market", "May learning curve sa branding"],
    commonMistakesTl: ["Walang portfolio site", "Di nag-ask ng brief bago gumawa"],
    steps: [
      {
        title: "Simulan",
        items: ["Gumawa ng 6–8 sample designs", "Mag-post sa FB/IG ng before-after", "Offer: 10 social graphics = ₱1,500–₱3,000"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "disenyo",
    avgPhpPerUnit: 800,
  }),
  H({
    slug: "social-media-manager",
    nameTl: "Social Media Manager",
    nameEn: "Social Media Manager",
    category: "Online / Remote",
    descriptionTl:
      "Pamahalaan ang FB/IG/TikTok pages ng small businesses: posting, captions, replies, basic analytics.",
    descriptionEn: "Manage social pages for small businesses.",
    incomeMinPhp: 10000,
    incomeMaxPhp: 40000,
    capitalMinPhp: 0,
    capitalMaxPhp: 0,
    hoursMinPerWeek: 10,
    hoursMaxPerWeek: 25,
    timeToFirstPesoDays: 21,
    breakevenMonths: 0,
    difficulty: "easy",
    regions: ["Nationwide"],
    requiresDevices: ["phone", "laptop"],
    requiresInternet: "data",
    skillsRequired: ["content", "communication"],
    legalRequirements: ["BIR (kung lumaki na)"],
    prosTl: ["Retainer-based income", "Pwede 2–4 clients"],
    consTl: ["Always-on expectations", "Content planning takes time"],
    commonMistakesTl: ["Walang content calendar", "Di nag-uusap ng scope bago magsimula"],
    steps: [
      {
        title: "Simulan",
        items: ["Gumawa ng sample content calendar (7 days)", "Pitch sa mga kainan/salon/tindahan sa area mo", "Package: ₱8K–₱15K/client/month"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "kliyente/buwan",
    avgPhpPerUnit: 8000,
  }),
  H({
    slug: "bookkeeping",
    nameTl: "Bookkeeping / Accounting Support",
    nameEn: "Bookkeeping Support",
    category: "Online / Remote",
    descriptionTl:
      "Mag-encode ng sales/expenses, reconciliation, at basic reports para sa MSMEs o foreign clients. Demand sa mga may accounting background.",
    descriptionEn: "Encode sales/expenses and reconcile books for MSMEs or foreign clients.",
    incomeMinPhp: 15000,
    incomeMaxPhp: 50000,
    capitalMinPhp: 0,
    capitalMaxPhp: 0,
    hoursMinPerWeek: 10,
    hoursMaxPerWeek: 25,
    timeToFirstPesoDays: 21,
    breakevenMonths: 0,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["laptop"],
    requiresInternet: "prepaid_wifi",
    skillsRequired: ["accounting", "admin", "english"],
    legalRequirements: ["BIR (kung lumaki na)"],
    prosTl: ["Recurring monthly clients", "Stable demand"],
    consTl: ["Kailangan ng accounting background", "Detail-heavy"],
    commonMistakesTl: ["Di marunong ng spreadsheet discipline", "Walang scope letter"],
    steps: [
      {
        title: "Simulan",
        items: ["Aralin ang Sheets/Excel + basic accounting terms", "Mag-offer sa OnlineJobs.ph", "Retainer: ₱8K–₱15K/client/month"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "kliyente/buwan",
    avgPhpPerUnit: 9000,
  }),

  // ─────────────────────── ONLINE SELLING ───────────────────────
  H({
    slug: "shopee-reseller",
    nameTl: "Shopee / Lazada Reseller",
    nameEn: "Shopee / Lazada Reseller",
    category: "Online Selling",
    descriptionTl:
      "Bumili ng items sa wholesale (malliit na batch muna), ibenta online. Focus sa fast-moving items.",
    descriptionEn: "Buy small wholesale batches then resell online.",
    incomeMinPhp: 5000,
    incomeMaxPhp: 50000,
    capitalMinPhp: 1000,
    capitalMaxPhp: 10000,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 25,
    timeToFirstPesoDays: 7,
    breakevenMonths: 1,
    difficulty: "easy",
    regions: ["Nationwide"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["sales", "customer_service"],
    legalRequirements: ["DTI (recommended habang lumalaki)", "BIR (kung tumagal na)"],
    prosTl: ["Madaling simulan", "Built-in buyers sa marketplaces"],
    consTl: ["Price war", "Platform fees + returns"],
    commonMistakesTl: ["Di binibilang ang fees at shipping", "Isang produkto lang, walang repeat winners"],
    steps: [
      {
        title: "Simulan",
        items: [
          "Hanap ng 2–3 products na mabilis umikot",
          "Compute: puhunan + platform fees + shipping + packaging",
          "Test muna sa ₱1K–₱2K na batch bago magpalaki",
        ],
      },
    ],
    suppliers: [
      {
        title: "Sourcing hints",
        links: [
          { label: "DTI Negosyo resources", url: "https://www.dti.gov.ph/negosyo/" },
        ],
      },
    ],
    legitimacyScore: 4,
    unitLabel: "order",
    avgPhpPerUnit: 60,
  }),
  H({
    slug: "tiktok-affiliate",
    nameTl: "TikTok Shop Affiliate",
    nameEn: "TikTok Shop Affiliate",
    category: "Online Selling",
    descriptionTl:
      "Kumita sa commission kapag may bumili gamit ang affiliate link mo. ₱0 puhunan, phone lang.",
    descriptionEn: "Earn commissions when people buy via your affiliate link.",
    incomeMinPhp: 3000,
    incomeMaxPhp: 80000,
    capitalMinPhp: 0,
    capitalMaxPhp: 1000,
    hoursMinPerWeek: 3,
    hoursMaxPerWeek: 20,
    timeToFirstPesoDays: 7,
    breakevenMonths: 0,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["content", "sales"],
    legalRequirements: ["None (sa start)", "BIR (kung consistent na)"],
    prosTl: ["₱0 puhunan", "Viral upside"],
    consTl: ["Unpredictable", "Kailangan ng consistency"],
    commonMistakesTl: ["Spam posting", "Walang niche", "Di nag-re-review ng product bago i-promote"],
    steps: [
      {
        title: "Simulan",
        items: ["Pumili ng niche (beauty, kitchen, school)", "1–2 videos/day for 14 days", "Gumamit ng honest demo + review"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    isTrending: true,
    unitLabel: "araw ng live selling",
    avgPhpPerUnit: 700,
  }),
  H({
    slug: "fb-marketplace-buy-sell",
    nameTl: "Facebook Marketplace Buy-and-Sell",
    nameEn: "Facebook Marketplace Buy-and-Sell",
    category: "Online Selling",
    descriptionTl:
      "Bumili ng undervalued items (gamit na gamit, surplus, ukay), linisin/i-photograph ng maayos, ibenta ng mas mahal.",
    descriptionEn: "Buy undervalued items, clean/rephotograph, resell higher.",
    incomeMinPhp: 3000,
    incomeMaxPhp: 30000,
    capitalMinPhp: 1000,
    capitalMaxPhp: 5000,
    hoursMinPerWeek: 3,
    hoursMaxPerWeek: 20,
    timeToFirstPesoDays: 5,
    breakevenMonths: 1,
    difficulty: "easy",
    regions: ["Nationwide", "Rural-friendly"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["sales"],
    legalRequirements: ["None (sa start)"],
    prosTl: ["Mabilis ang ikot ng pera", "No platform fees sa Marketplace"],
    consTl: ["May bogus buyers", "Meetup logistics"],
    commonMistakesTl: ["Di nag-i-inspect bago bumili", "Walang price research"],
    steps: [
      {
        title: "Simulan",
        items: ["Mag-scout ng undervalued items sa area mo", "Photograph sa natural light", "Meetup sa public places lang"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "item",
    avgPhpPerUnit: 200,
  }),
  H({
    slug: "ukay-online",
    nameTl: "Preloved / Ukay-Ukay Online",
    nameEn: "Preloved / Ukay-Ukay Online",
    category: "Online Selling",
    descriptionTl:
      "Bumili ng ukay bundles (Baguio/Taytay/Freedom), i-curate, at ibenta per piece online o sa live selling.",
    descriptionEn: "Buy ukay bundles, curate, and resell per piece online.",
    incomeMinPhp: 3000,
    incomeMaxPhp: 25000,
    capitalMinPhp: 1000,
    capitalMaxPhp: 5000,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 20,
    timeToFirstPesoDays: 7,
    breakevenMonths: 1,
    difficulty: "easy",
    regions: ["Nationwide", "Rural-friendly"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["sales"],
    legalRequirements: ["DTI (habang lumalaki)"],
    prosTl: ["Maliit ang puhunan", "Mataas ang margin per piece"],
    consTl: ["May rejects sa bundles", "Laundry/sorting time"],
    commonMistakesTl: ["Di binibilang ang rejects sa costing", "Di nilalabhan bago ibenta"],
    steps: [
      {
        title: "Simulan",
        items: ["1 bundle muna (₱1K–₱2K)", "Sort: premium / mid / thrift price", "Live selling o Sunny/album posting sa FB"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "item",
    avgPhpPerUnit: 80,
  }),
  H({
    slug: "digital-products",
    nameTl: "Digital Products (templates, ebooks)",
    nameEn: "Digital Products",
    category: "Online Selling",
    descriptionTl:
      "Gumawa ng Notion/Canva templates, resibo templates, budgeting sheets, o mini-ebooks. Ibesa nang paulit-ulit nang walang inventory.",
    descriptionEn: "Create templates and ebooks; sell repeatedly with no inventory.",
    incomeMinPhp: 2000,
    incomeMaxPhp: 50000,
    capitalMinPhp: 0,
    capitalMaxPhp: 1000,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 15,
    timeToFirstPesoDays: 14,
    breakevenMonths: 0,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["laptop"],
    requiresInternet: "prepaid_wifi",
    skillsRequired: ["writing", "graphic_design", "content"],
    legalRequirements: ["BIR (kung lumaki na)"],
    prosTl: ["Passive-ish income", "Walang shipping"],
    consTl: ["Slow start", "Kailangan ng marketing"],
    commonMistakesTl: ["Gumagawa na walang validation ng demand", "Di nag-u-update ng listings"],
    steps: [
      {
        title: "Simulan",
        items: ["Gumawa ng 1 product (hal. Peso Budget Tracker)", "I-post sa Gumroad o FB Page", "Promote sa groups + short videos"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "download",
    avgPhpPerUnit: 149,
  }),

  // ─────────────────────── FOOD & LOCAL NEGOSYO ───────────────────────
  H({
    slug: "home-baking",
    nameTl: "Home-based Baking (cakes, cookies)",
    nameEn: "Home-based Baking",
    category: "Food & Local Negosyo",
    descriptionTl:
      "Mag-bake ng cookies, cakes, at pastries mula sa bahay. Order-based, kaya kontrolado ang gastos.",
    descriptionEn: "Bake cookies and cakes from home, order-based.",
    incomeMinPhp: 5000,
    incomeMaxPhp: 40000,
    capitalMinPhp: 3000,
    capitalMaxPhp: 10000,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 20,
    timeToFirstPesoDays: 5,
    breakevenMonths: 1,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["phone"],
    requiresInternet: "any",
    skillsRequired: ["cooking"],
    legalRequirements: ["Barangay clearance (kung lalaki)"],
    prosTl: ["Order-based, walang sayang", "Repeat customers sa celebrations"],
    consTl: ["Seasonal spikes", "Physical labor"],
    commonMistakesTl: ["Di nako-compute ang ingredient + gas + box cost", "Super mura magpresyo"],
    steps: [
      {
        title: "Simulan",
        items: ["Pili ng 2–3 best-sellers muna", "I-photo ng maayos + price list", "I-post sa barangay/subdivision groups"],
      },
    ],
    suppliers: [],
    legitimacyScore: 5,
    unitLabel: "order",
    avgPhpPerUnit: 250,
    successStoryTl:
      "Halimbawa (illustrative): Si Ate Leng, nanay sa Laguna, nagsimula sa ₱3,500 puhunan at isang banana bread recipe. Sa subdivision group lang nag-post. After 6 months, may 10–15 orders siya kada weekend at ₱12K–₱18K net kada buwan.",
  }),
  H({
    slug: "frozen-goods-reselling",
    nameTl: "Frozen Goods Reselling (siomai, longganisa)",
    nameEn: "Frozen Goods Reselling",
    category: "Food & Local Negosyo",
    descriptionTl:
      "Mag-stock ng siomai, longganisa, tocino at ibenta sa kapitbahay/office. Mabilis ang ikot kapag malamig ang storage.",
    descriptionEn: "Stock frozen goods and resell to neighbors/office.",
    incomeMinPhp: 4000,
    incomeMaxPhp: 25000,
    capitalMinPhp: 2000,
    capitalMaxPhp: 8000,
    hoursMinPerWeek: 3,
    hoursMaxPerWeek: 15,
    timeToFirstPesoDays: 3,
    breakevenMonths: 1,
    difficulty: "easy",
    regions: ["Nationwide", "Rural-friendly"],
    requiresDevices: ["phone"],
    requiresInternet: "any",
    skillsRequired: ["sales"],
    legalRequirements: ["None (sa start)"],
    prosTl: ["Staple food = steady demand", "Maliit ang puhunan"],
    consTl: ["Kailangan ng freezer", "Thin margins per pack"],
    commonMistakesTl: ["Di mino-monitor ang brownout risk", "Walang inventory record"],
    steps: [
      {
        title: "Simulan",
        items: ["Hanap ng supplier (direct distributor = mas mura)", "Simula sa 3–5 SKUs", "Sabihan ang kapitbahay + GCash payment"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "pack",
    avgPhpPerUnit: 20,
  }),
  H({
    slug: "milk-tea-cart",
    nameTl: "Milk Tea / Coffee Cart",
    nameEn: "Milk Tea / Coffee Cart",
    category: "Food & Local Negosyo",
    descriptionTl:
      "Maliit na cart sa school/office areas o events. Mataas ang volume kapag maganda ang location.",
    descriptionEn: "Small cart near schools/offices/events.",
    incomeMinPhp: 10000,
    incomeMaxPhp: 60000,
    capitalMinPhp: 15000,
    capitalMaxPhp: 60000,
    hoursMinPerWeek: 20,
    hoursMaxPerWeek: 40,
    timeToFirstPesoDays: 7,
    breakevenMonths: 4,
    difficulty: "medium",
    regions: ["NCR", "Luzon", "Visayas", "Mindanao"],
    requiresDevices: [],
    requiresInternet: "any",
    skillsRequired: ["sales", "customer_service", "cooking"],
    legalRequirements: ["Barangay clearance", "Mayor's permit", "Sanitary permit"],
    prosTl: ["High volume", "Daily cash flow"],
    consTl: ["Location-dependent", "Permits needed", "Physical setup"],
    commonMistakesTl: ["Sobrang laki ng puhunan sa setup bago may proof of demand", "Di na-test ng location"],
    steps: [
      {
        title: "Simulan",
        items: ["I-test muna sa weekend pop-up bago mag-cart", "Compute cost per cup (aim 40%+ margin)", "Ayusin ang barangay requirements ng maaga"],
      },
    ],
    suppliers: [],
    legitimacyScore: 3,
    unitLabel: "tasa",
    avgPhpPerUnit: 18,
  }),
  H({
    slug: "sari-sari-store",
    nameTl: "Sari-Sari Store",
    nameEn: "Sari-Sari Store",
    category: "Food & Local Negosyo",
    descriptionTl:
      "Classic Pinoy negosyo: tingi-tingi essentials sa bahay. Mababa ang margin pero steady ang volume sa maayos na pwesto.",
    descriptionEn: "Classic neighborhood retail store from home.",
    incomeMinPhp: 5000,
    incomeMaxPhp: 30000,
    capitalMinPhp: 15000,
    capitalMaxPhp: 50000,
    hoursMinPerWeek: 20,
    hoursMaxPerWeek: 60,
    timeToFirstPesoDays: 2,
    breakevenMonths: 3,
    difficulty: "medium",
    regions: ["Nationwide", "Rural-friendly"],
    requiresDevices: [],
    requiresInternet: "any",
    skillsRequired: ["sales"],
    legalRequirements: ["Barangay clearance", "Mayor's permit (recommended)"],
    prosTl: ["Daily cash flow", "Community staple"],
    consTl: ["Thin margins", "Debt/pautang management", "Long hours"],
    commonMistakesTl: ["Sobrang daming pa-utang", "Walang record ng benta at bulsa"],
    steps: [
      {
        title: "Simulan",
        items: ["Start sa fast-moving essentials", "Iwasan ang pa-utang sa simula", "Record-keeping kahit notebook lang"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "araw",
    avgPhpPerUnit: 350,
    successStoryTl:
      "Halimbawa (illustrative): Si Tatay Rodel, dating tricycle driver sa Batangas, nagtayo ng sari-sari sa harap ng bahay gamit ang ₱20K na ipon. Simula sa soft drinks, bigas, at load. After 1 taon, ₱400–₱600 net kada araw.",
  }),

  // ─────────────────────── GIG ECONOMY ───────────────────────
  H({
    slug: "ride-hailing-rider",
    nameTl: "Grab / Angkas / MoveIt Rider",
    nameEn: "Ride-hailing Rider",
    category: "Gig Economy",
    descriptionTl:
      "Mag-motorcycle ride-hailing sa mga major cities. Best kung may motor ka na at alam ang peak hours.",
    descriptionEn: "Motorcycle ride-hailing in major cities.",
    incomeMinPhp: 15000,
    incomeMaxPhp: 35000,
    capitalMinPhp: 0,
    capitalMaxPhp: 20000,
    hoursMinPerWeek: 15,
    hoursMaxPerWeek: 40,
    timeToFirstPesoDays: 3,
    breakevenMonths: 0,
    difficulty: "easy",
    regions: ["NCR", "Visayas", "Mindanao"],
    requiresDevices: ["phone", "motor"],
    requiresInternet: "data",
    skillsRequired: ["delivery", "customer_service"],
    legalRequirements: ["Professional driver's license (platform requirement)"],
    prosTl: ["Kita agad", "Flexible schedule"],
    consTl: ["Wear and tear sa motor", "Biyahe risks", "Weather-dependent"],
    commonMistakesTl: ["Di nag-iipon para sa maintenance", "Biyahe kahit alanganing panahon"],
    steps: [
      {
        title: "Simulan",
        items: ["Siguraduhin kumpleto ang lisensya at rehistro", "Mag-apply sa 1 platform muna", "I-master ang peak hours + surge areas"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "biyahe",
    avgPhpPerUnit: 60,
    successStoryTl:
      "Halimbawa (illustrative): Si Koyah, 26, dating warehouse staff sa Pasig. May motor na kaya ₱0 puhunan. Bumibiyahe 4 na oras bago ang day shift niya — ₱800–₱1,200 kada araw on top ng sweldo.",
  }),
  H({
    slug: "food-delivery-rider",
    nameTl: "Foodpanda / GrabFood Rider",
    nameEn: "Food Delivery Rider",
    category: "Gig Economy",
    descriptionTl:
      "Mag-deliver ng food sa mga major cities. Pwede motor o bisikleta depende sa zone.",
    descriptionEn: "Deliver food in major cities.",
    incomeMinPhp: 12000,
    incomeMaxPhp: 30000,
    capitalMinPhp: 0,
    capitalMaxPhp: 15000,
    hoursMinPerWeek: 15,
    hoursMaxPerWeek: 40,
    timeToFirstPesoDays: 3,
    breakevenMonths: 0,
    difficulty: "easy",
    regions: ["NCR", "Visayas", "Mindanao"],
    requiresDevices: ["phone", "motor"],
    requiresInternet: "data",
    skillsRequired: ["delivery"],
    legalRequirements: ["Platform requirements (ID, license)"],
    prosTl: ["Mabilis ang payout cycle", "Demand sa lunch/dinner peaks"],
    consTl: ["Fuel costs", "Peak-only earnings"],
    commonMistakesTl: ["Di mino-monitor ang fuel vs kita", "Di gumagamit ng insulated bag — madaming refund issues"],
    steps: [
      {
        title: "Simulan",
        items: ["Kumpletuhin ang platform requirements", "Mag-setup ng GCash para sa payouts", "Target ang meal-peak hours"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "biyahe",
    avgPhpPerUnit: 50,
  }),
  H({
    slug: "lalamove-driver",
    nameTl: "Lalamove / Transportify Driver",
    nameEn: "Delivery Van/Truck Driver",
    category: "Gig Economy",
    descriptionTl:
      "Kung may van, pickup, o MPV ka, mas malaki ang biyahe sa parcel/bulk deliveries.",
    descriptionEn: "Van/truck deliveries via Lalamove/Transportify.",
    incomeMinPhp: 20000,
    incomeMaxPhp: 50000,
    capitalMinPhp: 0,
    capitalMaxPhp: 20000,
    hoursMinPerWeek: 20,
    hoursMaxPerWeek: 45,
    timeToFirstPesoDays: 5,
    breakevenMonths: 0,
    difficulty: "medium",
    regions: ["NCR", "Luzon"],
    requiresDevices: ["phone", "car"],
    requiresInternet: "data",
    skillsRequired: ["delivery", "customer_service"],
    legalRequirements: ["Professional license", "OR/CR updated"],
    prosTl: ["Mas malaking biyahe per booking", "Business clients"],
    consTl: ["Vehicle costs", "Long waits sa warehouses"],
    commonMistakesTl: ["Di binibilang ang toll + gas sa bookings", "Tumatanggap ng overload na biyahe"],
    steps: [
      {
        title: "Simulan",
        items: ["Mag-register sa Lalamove/Transportify partner", "I-ready ang vehicle photos at papers", "Start sa short-distance bookings"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "booking",
    avgPhpPerUnit: 250,
  }),
  H({
    slug: "errand-service",
    nameTl: "Errand / Padala Service",
    nameEn: "Errand / Padala Service",
    category: "Gig Economy",
    descriptionTl:
      "Mag-pabili ng groceries, mag-bayad ng bills, mag-deliver ng packages sa loob ng lungsod/barangay mo.",
    descriptionEn: "Run local errands and deliveries for a fee.",
    incomeMinPhp: 5000,
    incomeMaxPhp: 20000,
    capitalMinPhp: 0,
    capitalMaxPhp: 500,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 25,
    timeToFirstPesoDays: 2,
    breakevenMonths: 0,
    difficulty: "easy",
    regions: ["Nationwide", "Rural-friendly"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["delivery", "customer_service"],
    legalRequirements: ["None (barangay-scale)"],
    prosTl: ["₱0 puhunan", "Community trust ang puhunan"],
    consTl: ["Per-errand basis ang kita", "Scope creep"],
    commonMistakesTl: ["Walang malinaw na fee structure", "Di nag-va-verify ng items bago ihatid"],
    steps: [
      {
        title: "Simulan",
        items: ["I-post ang services + rates sa barangay group", "Singil per errand + distance fee", "GCash payment para mabilis"],
      },
    ],
    suppliers: [],
    legitimacyScore: 5,
    unitLabel: "errand",
    avgPhpPerUnit: 100,
  }),

  // ─────────────────────── LOCAL SERVICES ───────────────────────
  H({
    slug: "home-tutoring",
    nameTl: "Home Tutoring (K-12)",
    nameEn: "Home Tutoring (K-12)",
    category: "Local Services",
    descriptionTl:
      "Mag-tutor ng Math/Science/English sa kapitbahay o online. Mabilis ang pera, walang puhunan.",
    descriptionEn: "Tutor Math/Science/English locally or online.",
    incomeMinPhp: 5000,
    incomeMaxPhp: 30000,
    capitalMinPhp: 0,
    capitalMaxPhp: 500,
    hoursMinPerWeek: 2,
    hoursMaxPerWeek: 15,
    timeToFirstPesoDays: 3,
    breakevenMonths: 0,
    difficulty: "easy",
    regions: ["Nationwide", "Rural-friendly"],
    requiresDevices: ["phone"],
    requiresInternet: "any",
    skillsRequired: ["teaching", "communication"],
    legalRequirements: ["None"],
    prosTl: ["Mabilis ang pera", "Recurring weekly schedule"],
    consTl: ["Kailangan tiwala ng magulang", "Prep time"],
    commonMistakesTl: ["Walang lesson structure", "Di nag-se-set ng cancellation policy"],
    steps: [
      {
        title: "Simulan",
        items: ["Mag-post sa barangay/parent groups", "Offer 1 free trial session", "₱200–₱400/sesyon depende sa level"],
      },
    ],
    suppliers: [],
    legitimacyScore: 5,
    unitLabel: "sesyon",
    avgPhpPerUnit: 300,
    successStoryTl:
      "Halimbawa (illustrative): Si Trisha, 21, 3rd-year BSEd student sa Iloilo. Nagtututor ng 4 na estudyante, tig-2 sesyon kada linggo, ₱300 kada sesyon. ₱9,600/buwan habang nag-aaral.",
  }),
  H({
    slug: "home-salon-nails",
    nameTl: "Home Salon / Nails / Lashes",
    nameEn: "Home Salon / Nails / Lashes",
    category: "Local Services",
    descriptionTl:
      "Manicure, pedicure, lash extensions, o hair services sa bahay o home-service. High repeat rate.",
    descriptionEn: "Nails/lashes/hair services at home or home-service.",
    incomeMinPhp: 8000,
    incomeMaxPhp: 40000,
    capitalMinPhp: 5000,
    capitalMaxPhp: 20000,
    hoursMinPerWeek: 10,
    hoursMaxPerWeek: 30,
    timeToFirstPesoDays: 7,
    breakevenMonths: 1,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["phone"],
    requiresInternet: "any",
    skillsRequired: ["beauty", "customer_service"],
    legalRequirements: ["Barangay clearance (kung may walk-in)"],
    prosTl: ["High repeat customers", "Word-of-mouth ang marketing"],
    consTl: ["Kailangan ng training/certification", "Hygiene-critical"],
    commonMistakesTl: ["Skip sa hygiene protocols — isang issue, sira ang reputation", "Di nag-re-raise ng prices"],
    steps: [
      {
        title: "Simulan",
        items: ["Mag-training muna (TESDA o workshops)", "I-build ang portfolio sa IG/TikTok", "Simulang sa pamilya/kapitbahay na rates"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "kliyente",
    avgPhpPerUnit: 350,
  }),
  H({
    slug: "aircon-cleaning",
    nameTl: "Aircon Cleaning",
    nameEn: "Aircon Cleaning",
    category: "Local Services",
    descriptionTl:
      "Maglinis ng aircon units (split-type/window) sa mga bahay at small offices. Mababaw ang learning curve, mataas ang demand.",
    descriptionEn: "Clean aircon units for homes and small offices.",
    incomeMinPhp: 10000,
    incomeMaxPhp: 40000,
    capitalMinPhp: 8000,
    capitalMaxPhp: 20000,
    hoursMinPerWeek: 10,
    hoursMaxPerWeek: 30,
    timeToFirstPesoDays: 7,
    breakevenMonths: 2,
    difficulty: "medium",
    regions: ["NCR", "Luzon", "Visayas", "Mindanao"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["repair"],
    legalRequirements: ["None (sa start)"],
    prosTl: ["Seasonal surge (summer)", "Repeat every 3–6 months"],
    consTl: ["Tools puhunan", "Physical work"],
    commonMistakesTl: ["Walang pressure washer discipline — nasasira ang fins", "Di nag-ba-bundle ng services"],
    steps: [
      {
        title: "Simulan",
        items: ["Mag-aral sa tutorials + mag-practice sa sariling unit", "Bumili ng basic tools (₱8K–₱15K)", "Charge ₱500–₱800/unit"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "unit",
    avgPhpPerUnit: 600,
  }),
  H({
    slug: "phone-repair",
    nameTl: "Phone / Computer Repair",
    nameEn: "Phone / Computer Repair",
    category: "Local Services",
    descriptionTl:
      "Magpalit ng screens, batteries, software fixes. Puhunan sa tools at konting spare parts.",
    descriptionEn: "Screen/battery/software repairs.",
    incomeMinPhp: 8000,
    incomeMaxPhp: 35000,
    capitalMinPhp: 5000,
    capitalMaxPhp: 15000,
    hoursMinPerWeek: 10,
    hoursMaxPerWeek: 30,
    timeToFirstPesoDays: 7,
    breakevenMonths: 2,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["repair", "tech"],
    legalRequirements: ["None (sa start)"],
    prosTl: ["Steady demand", "High trust moats"],
    consTl: ["Skill-critical", "Liability sa maling repair"],
    commonMistakesTl: ["Tumatanggap ng repair na lampas sa skill", "Walang warranty policy"],
    steps: [
      {
        title: "Simulan",
        items: ["Mag-practice sa sariling/sirang units", "Start sa screen at battery replacements", "Bigyan ng 7-day service warranty"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "repair",
    avgPhpPerUnit: 350,
  }),
  H({
    slug: "laundry-service",
    nameTl: "Laundry / Labada Service",
    nameEn: "Laundry Service",
    category: "Local Services",
    descriptionTl:
      "Mag-laundry service sa mga dorm, apartments, at subdivisions. Pickup + delivery = premium pricing.",
    descriptionEn: "Laundry service for dorms/apartments with pickup + delivery.",
    incomeMinPhp: 8000,
    incomeMaxPhp: 35000,
    capitalMinPhp: 10000,
    capitalMaxPhp: 40000,
    hoursMinPerWeek: 15,
    hoursMaxPerWeek: 40,
    timeToFirstPesoDays: 7,
    breakevenMonths: 2,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["customer_service"],
    legalRequirements: ["Barangay clearance"],
    prosTl: ["Recurring customers", "Simple operations"],
    consTl: ["Utility costs", "Lost/damaged item disputes"],
    commonMistakesTl: ["Walang towel/tag system — naililiito ang labahan", "Di binibilang ang kuryente + tubig sa presyo"],
    steps: [
      {
        title: "Simulan",
        items: ["₱100–₱150/load ang baseline", "Target ang dorm areas", "Tag every load + photo confirmation"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "karga",
    avgPhpPerUnit: 130,
  }),

  // ─────────────────────── AGRI & PROVINCIAL ───────────────────────
  H({
    slug: "backyard-poultry",
    nameTl: "Backyard Poultry (native chicken, itik)",
    nameEn: "Backyard Poultry",
    category: "Agri & Provincial",
    descriptionTl:
      "Mag-alaga ng native chicken o itik sa bakuran. Ibenta ang karne at itlog sa palengke o kapitbahay.",
    descriptionEn: "Raise native chickens/ducks; sell meat and eggs.",
    incomeMinPhp: 3000,
    incomeMaxPhp: 20000,
    capitalMinPhp: 5000,
    capitalMaxPhp: 20000,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 20,
    timeToFirstPesoDays: 60,
    breakevenMonths: 3,
    difficulty: "medium",
    regions: ["Rural-friendly", "Nationwide"],
    requiresDevices: [],
    requiresInternet: "any",
    skillsRequired: ["agri"],
    legalRequirements: ["None (barangay-scale)"],
    prosTl: ["Dual income: meat + eggs", "Scalable"],
    consTl: ["Disease risk", "Feed costs"],
    commonMistakesTl: ["Skip sa vaccination", "Sobrang madami agad ang alaga"],
    steps: [
      {
        title: "Simulan",
        items: ["Start sa 10–20 heads", "Secure ang housing laban sa predators", "I-record ang feed vs. weight"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "ulo",
    avgPhpPerUnit: 120,
    successStoryTl:
      "Halimbawa (illustrative): Si Aling Baby, Leyte, nagsimula sa 15 native chickens. Binebenta ang itlog sa kapitbahay (₱10/pc) at karne tuwing fiesta season. ₱4K–₱6K extra income kada buwan.",
  }),
  H({
    slug: "mushroom-growing",
    nameTl: "Mushroom Growing",
    nameEn: "Mushroom Growing",
    category: "Agri & Provincial",
    descriptionTl:
      "Magtanim ng oyster mushrooms sa maliit na space. Mataas ang value per kilo at mabilis ang harvest cycle.",
    descriptionEn: "Grow oyster mushrooms in small spaces.",
    incomeMinPhp: 5000,
    incomeMaxPhp: 25000,
    capitalMinPhp: 5000,
    capitalMaxPhp: 15000,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 15,
    timeToFirstPesoDays: 45,
    breakevenMonths: 2,
    difficulty: "medium",
    regions: ["Rural-friendly", "Nationwide"],
    requiresDevices: [],
    requiresInternet: "any",
    skillsRequired: ["agri"],
    legalRequirements: ["None (sa start)"],
    prosTl: ["Mabilis ang harvest", "High value per kilo"],
    consTl: ["Temperature-sensitive", "Must sell fresh fast"],
    commonMistakesTl: ["Walang buyer bago mag-harvest", "Contamination sa fruiting bags"],
    steps: [
      {
        title: "Simulan",
        items: ["Bumili ng ready-to-fruit bags muna", "I-test ang market sa kapitbahay/gulayan", "₱150–₱250/kilo ang presyo"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
    unitLabel: "kilo",
    avgPhpPerUnit: 100,
  }),
  H({
    slug: "ornamental-plants",
    nameTl: "Ornamental Plants / Succulents",
    nameEn: "Ornamental Plants",
    category: "Agri & Provincial",
    descriptionTl:
      "Mag-propagate ng succulents at halamang pandekorasyon. Ibenta online o sa weekend markets.",
    descriptionEn: "Propagate succulents and decorative plants; sell online.",
    incomeMinPhp: 3000,
    incomeMaxPhp: 20000,
    capitalMinPhp: 2000,
    capitalMaxPhp: 10000,
    hoursMinPerWeek: 3,
    hoursMaxPerWeek: 15,
    timeToFirstPesoDays: 21,
    breakevenMonths: 1,
    difficulty: "easy",
    regions: ["Nationwide", "Rural-friendly"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["agri", "sales"],
    legalRequirements: ["None (sa start)"],
    prosTl: ["Ganda ang margins sa rare varieties", "Relaxing hobby-turned-business"],
    consTl: ["Slow propagation", "Price drops kapag common na ang variety"],
    commonMistakesTl: ["Overwatering", "Bumibili ng mahal na mother plants bago may buyers"],
    steps: [
      {
        title: "Simulan",
        items: ["Start sa hardy varieties", "I-photo sa natural light", "I-post sa plant groups + Marketplace"],
      },
    ],
    suppliers: [],
    legitimacyScore: 5,
    unitLabel: "paso",
    avgPhpPerUnit: 60,
  }),

  // ─────────────────────── CONTENT & CREATIVE ───────────────────────
  H({
    slug: "tiktok-creator",
    nameTl: "TikTok Creator",
    nameEn: "TikTok Creator",
    category: "Content & Creative",
    descriptionTl:
      "Gumawa ng content sa niche mo (food, study, comedy, finance-Tagalog). Kita sa gifts, brand deals, at affiliate.",
    descriptionEn: "Create niche content; earn via gifts, brand deals, affiliates.",
    incomeMinPhp: 2000,
    incomeMaxPhp: 80000,
    capitalMinPhp: 0,
    capitalMaxPhp: 1000,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 25,
    timeToFirstPesoDays: 30,
    breakevenMonths: 0,
    difficulty: "hard",
    regions: ["Nationwide"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["content", "video_editing"],
    legalRequirements: ["BIR (kung lumaki na ang kita)"],
    prosTl: ["₱0 puhunan", "Unlimited upside"],
    consTl: ["Sobrang unpredictable", "Months bago kumita"],
    commonMistakesTl: ["Walang niche", "Copy-paste content", "Sumusuko bago ang 90 days"],
    steps: [
      {
        title: "Simulan",
        items: ["Pumili ng 1 niche + 1 format", "1–2 videos/day for 90 days", "I-track kung alin ang nagwo-work, doblehin iyon"],
      },
    ],
    suppliers: [],
    legitimacyScore: 3,
  }),
  H({
    slug: "youtube-channel",
    nameTl: "YouTube Channel",
    nameEn: "YouTube Channel",
    category: "Content & Creative",
    descriptionTl:
      "Long-term play: gumawa ng videos sa expertise/hobby mo. Matagal bago kumita pero compounding.",
    descriptionEn: "Long-term content play with compounding returns.",
    incomeMinPhp: 0,
    incomeMaxPhp: 100000,
    capitalMinPhp: 0,
    capitalMaxPhp: 5000,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 30,
    timeToFirstPesoDays: 120,
    breakevenMonths: 6,
    difficulty: "hard",
    regions: ["Nationwide"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["content", "video_editing"],
    legalRequirements: ["BIR (pag monetized)"],
    prosTl: ["Compounding library", "Evergreen income"],
    consTl: ["4–12 months bago ang kita", "High effort per video"],
    commonMistakesTl: ["Iniiwan bago ang 100 videos", "Walang search intent sa topics"],
    steps: [
      {
        title: "Simulan",
        items: ["Filipino-language tutorials ang madaling rank", "1 long-form/week or 3 shorts/week", "Study analytics every month"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
  }),
  H({
    slug: "affiliate-marketing",
    nameTl: "Affiliate Marketing (Shopee/Lazada/TikTok)",
    nameEn: "Affiliate Marketing",
    category: "Content & Creative",
    descriptionTl:
      "Mag-promote ng products gamit ang affiliate links sa blog, TikTok, o FB page. Commission-based.",
    descriptionEn: "Promote products with affiliate links; commission-based.",
    incomeMinPhp: 2000,
    incomeMaxPhp: 60000,
    capitalMinPhp: 0,
    capitalMaxPhp: 500,
    hoursMinPerWeek: 5,
    hoursMaxPerWeek: 20,
    timeToFirstPesoDays: 14,
    breakevenMonths: 0,
    difficulty: "medium",
    regions: ["Nationwide"],
    requiresDevices: ["phone"],
    requiresInternet: "data",
    skillsRequired: ["content", "sales"],
    legalRequirements: ["BIR (kung lumaki na)"],
    prosTl: ["Walang inventory", "Stackable sa ibang raket"],
    consTl: ["Kailangan ng traffic muna", "Low commissions sa iba"],
    commonMistakesTl: ["Nag-spa-spam ng links", "Di dinidisclose ang affiliate relationship"],
    steps: [
      {
        title: "Simulan",
        items: ["Mag-apply sa Shopee/Lazada affiliate program", "Gumawa ng honest reviews/comparisons", "I-track kung aling platform ang nagko-convert"],
      },
    ],
    suppliers: [],
    legitimacyScore: 4,
  }),
];

const sampleRegistry = [
  {
    entityName: "Training Fee First",
    aliases: ["registration fee", "slot fee", "training fee", "reservation fee"],
    riskLevel: "high" as const,
    source: "internal",
    notes: "Red flag pattern: upfront payment bago kumita.",
  },
  {
    entityName: "OTP / PIN Requests",
    aliases: ["gcash pin", "otp", "one-time password", "verification code"],
    riskLevel: "high" as const,
    source: "internal",
    notes: "Wag kailanman mag-share ng OTP o GCash/Maya PIN kahit kanino.",
  },
  {
    entityName: "Guaranteed ROI Investment",
    aliases: ["double your money", "guaranteed profit", "100% roi", "no risk investment"],
    riskLevel: "high" as const,
    source: "internal",
    notes: "Ponzi/pyramid pattern. Cross-check sa SEC advisory list.",
  },
  {
    entityName: "Recruitment-based Earnings",
    aliases: ["downline", "upline", "invite to earn", "recruit to earn"],
    riskLevel: "high" as const,
    source: "internal",
    notes: "Kung ang kita ay galing sa pagre-recruit at hindi sa produkto, pyramid scheme pattern iyan.",
  },
];

const sampleLegalGuides = [
  {
    slug: "kailangan-ko-ba-mag-register",
    titleTl: "Kailangan ko ba mag-register? (Decision Tree)",
    titleEn: "Do I need to register?",
    agency: "DTI / BIR",
    bodyTl:
      "**GABAY LANG ITO, HINDI LEGAL O TAX ADVICE.**\n\nItanong sa sarili mo:\n\n1) Minsanan / hobby lang ba?\n→ Halimbawa: isang beses kang nagbenta ng lumang phone mo. Kadalasan, hindi mo pa kailangan mag-register.\n\n2) May tuloy-tuloy ka bang benta o kliyente buwan-buwan?\n→ Kung oo, ikaw ay effectively may business o freelance income. Ito ang tamang panahon para ihanda ang BIR registration.\n\n3) Freelancer ka ba o nagbebenta ng products?\n→ Freelance (services): BIR muna ang priority.\n→ Products/negosyo: DTI business name + BIR + (sa tamang panahon) barangay/mayor's permit.\n\n4) May humihingi ba ng official receipt?\n→ Oo? Kailangan mo na talagang mag-register sa BIR.\n\n**Bottom line:** Hindi mo kailangang mag-register sa unang bente mo. Pero kapag consistent na ang kita (‎≈ ₱5K–₱10K/buwan pataas), simulan mo nang ayusin. Mas madali itong gawin nang maaga kaysa habulin sa late fees.",
    bodyEn:
      "If you earn consistently (regular clients/sales), prepare for BIR registration. Product businesses typically need DTI business name first. Occasional hobby sales usually don't require registration yet.",
  },
  {
    slug: "dti-business-name",
    titleTl: "DTI Business Name (BNRS) — Mabilisang Gabay",
    titleEn: "DTI Business Name (BNRS)",
    agency: "DTI",
    bodyTl:
      "**GABAY LANG ITO.** Para sa sole proprietors ang DTI Business Name.\n\n**Mga hakbang:**\n1) Isipin ang 2–3 name options (kailangan unique)\n2) Mag-apply online sa BNRS (bnrs.dti.gov.ph)\n3) Bayaran ang fee — depende sa territorial scope:\n   • Barangay (pinakamura)\n   • City/Municipality\n   • Regional\n   • National (pinakamahal)\n4) I-download at i-save ang certificate — valid ito ng 5 taon\n\n**Tip:** Kung maliit pa lang ang negosyo mo, barangay o city scope muna. Pwede mo itong i-renew/palitan later.",
    bodyEn:
      "For sole proprietors. Apply online at BNRS, choose territorial scope (barangay is cheapest), pay fee, save certificate (valid 5 years).",
  },
  {
    slug: "bir-freelancer-basics",
    titleTl: "BIR Basics para sa Freelancer (8% vs. Graduated)",
    titleEn: "BIR Basics for Freelancers",
    agency: "BIR",
    bodyTl:
      "**GABAY LANG ITO.**\n\nDalawang common tax options para sa self-employed/freelancers:\n\n**1) 8% Flat Rate**\n• Simpler computation\n• 8% ng gross income na lalampas sa ₱250,000/taon\n• Hindi na kailangan ng percentage tax\n\n**2) Graduated Rates**\n• Standard income tax table\n• May itemized deductions o OSD (optional standard deduction)\n• Mas OK kapag mataas ang expenses mo\n\n**Ano ang kakailanganin mo:**\n• Form 1901 (registration)\n• Certificate of Registration (COR)\n• Books of Accounts\n• Official Receipts / invoices\n• Quarterly filing deadlines (markahan sa calendar!)\n\n**Tip:** Kung below ₱250K ang taunang kita mo, maaaring exempt ka sa income tax — pero ang registration ay ibang usapan. Kumonsulta sa accountant o itanong sa BIR district office mo.",
    bodyEn:
      "Two options: 8% flat on gross over ₱250K, or graduated rates with deductions. You'll need Form 1901, COR, books, receipts, and quarterly filings.",
  },
  {
    slug: "sss-philhealth-pagibig",
    titleTl: "SSS, PhilHealth, at Pag-IBIG para sa Self-Employed",
    titleEn: "SSS, PhilHealth, Pag-IBIG for the Self-Employed",
    agency: "SSS / PhilHealth / Pag-IBIG",
    bodyTl:
      "**GABAY LANG ITO.**\n\nKung freelancer o may-ari ng maliit na negosyo ka, pwede kang mag-contribute bilang **voluntary/self-employed**:\n\n**SSS**\n• Protection sa sickness, maternity, disability, retirement\n• Mag-register online sa My.SSS\n• Contribution base sa napiling monthly salary credit\n\n**PhilHealth**\n• Health insurance coverage\n• Mag-register online o sa opisina\n• Premium computation base sa income\n\n**Pag-IBIG**\n• MP2 savings program — government-backed, mataas ang dividend vs. regular savings\n• Housing loan eligibility\n• Pwede sa minimum contribution, pwede ring dagdagan\n\n**Tip:** Kahit maliit ang kita sa simula, consistent contributions ang importante — ito ang social safety net mo.",
    bodyEn:
      "Self-employed Filipinos can contribute voluntarily: SSS (retirement/benefits), PhilHealth (health), Pag-IBIG + MP2 (savings). Register online; start small but be consistent.",
  },
  {
    slug: "online-seller-rules",
    titleTl: "Online Seller Rules (Internet Transactions Act Basics)",
    titleEn: "Online Seller Rules (RA 11967)",
    agency: "DTI",
    bodyTl:
      "**GABAY LANG ITO.** Ang RA 11967 (Internet Transactions Act) ay nagse-set ng rules para sa e-commerce.\n\n**Mga dapat tandaan bilang online seller:**\n• Tapat na product descriptions — walang misleading claims\n• Malinaw ang pricing (kasama ang fees at shipping)\n• May return/refund policy ka\n• Protektahan ang buyer data (Data Privacy Act)\n• Ang marketplaces (Shopee/Lazada) ay may sariling seller obligations\n\n**Bakit ito importante:** Kapag lumaki ang negosyo mo, may accountability ka sa mga bumibili sa'yo. Maagang mag-practice ng maayos na records at policies.\n\n**Reminder:** Hindi ito kompletong legal summary — basahin ang official IRR o kumonsulta sa DTI para sa details.",
    bodyEn:
      "RA 11967 sets e-commerce rules: honest descriptions, clear pricing, return policies, buyer data protection. Marketplaces have their own seller obligations.",
  },
];

export async function seedCoreData() {
  await db.insert(hustles).values(sampleHustles).onConflictDoNothing({ target: hustles.slug });
  await db
    .insert(scamRegistry)
    .values(sampleRegistry)
    .onConflictDoNothing({ target: scamRegistry.entityName });
  await db.insert(legalGuides).values(sampleLegalGuides).onConflictDoNothing({ target: legalGuides.slug });
}
